import {Inter, Roboto} from 'next/font/google'
import localFont from 'next/font/local'

import type {Metadata} from 'next'

import './_styles/globals.css'

import {getWagmiCookie} from '@/lib/actions/getWagmiCookie'
import {cn} from '@/lib/utils'
import {Navbar} from '@/components/navbar'
import {Provider} from '@/components/providers'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})
const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-robo',
})
const geoFont = localFont({
  src: [
    {
      path: './_styles/fonts/geomanist-regular-webfont.woff2',
      weight: '400',
    },
    {
      path: './_styles/fonts/geomanist-medium-webfont.woff2',
      weight: '500',
    },
    {
      path: './_styles/fonts/geomanist-bold-webfont.woff2',
      weight: '700',
    },
  ],
  variable: '--font-geo',
  preload: true,
  fallback: ['sans-serif'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = getWagmiCookie()

  return (
    <html lang="en">
      <body
        className={cn(
          'relative flex min-h-screen flex-col justify-center font-geo antialiased',
          inter.variable,
          geoFont.variable,
          roboto.variable
        )}
      >
        <Provider initialState={initialState}>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
